### ISSUE TITLE
Custom Task and xml export

### ISSUE THREAD

**Issue by biggosh** [sartography/SpiffWorkflow#102]
If a new task is written and the the workflow is exported, the procedure raises an error because it does not know how to map the task with a python class.

this mapping is hard coded in an array and it's not updateable from the custom class.

BG

**Comment by calexh-sar** [comment]
@biggosh I am with Sartography and we just released [Version 1.0](https://github.com/sartography/SpiffWorkflow/releases/tag/1.0) and very likely this issue was addressed if you are still interested.  Please let us know if you see otherwise or would like to discuss further.

**Comment by biggosh** [comment]
At the moment I can't check: I rewrote many parts of the code for the project I closed last year.
