### ISSUE TITLE
Easiest way to learn workplace patterns with SpiffWorkflow?

### ISSUE THREAD

**Issue by CapnKernel** [sartography/SpiffWorkflow#106]
Hello,

I have no experience with workflow, but I can see that the patterns described by the Workflow Patterns Initiative can be used to model workflows within business, and that SpiffWorkflow can be used to implement a system based on these patterns.  What I'm struggling with is learning all the patterns in a way that I can eventually use them for my own needs.

I bought Workflow Patterns - The Definitive Guide, but it's just too opaque for me to be useful.

Can anyone suggest a gentler introduction to learning how to implement workflow-based systems with SpiffWorkflow?

**Comment by danfunk** [comment]
My team is drawing our patterns out in BPMN, and we've used "BPMN Quick and Easy Using Method and Style" by Bruce Silver to wrap our heads around best practices for defining workflows using that notation.

**Comment by calexh-sar** [comment]
@CapnKernel we have also recently update [the Spiffworkflow readthe docs](https://spiffworkflow.readthedocs.io/en/latest/), in case they are of benefit.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
