### ISSUE TITLE
is there a Visualization tool of flow xml and json？

### ISSUE THREAD

**Issue by livizy** [sartography/SpiffWorkflow#107]
I realize that the spiff workflow spec(xml or json) is different from bpmn. And there is a Visualization edit tool online:https://demo.bpmn.io/new. So is there Visualization tool for spiff flow xml and json？

**Comment by Mabloq** [comment]
Want this too!!

**Comment by fahdAghribi** [comment]
using BPMN.IO javascript library its can be done easly and export xml for engine

**Comment by calexh-sar** [comment]
@livizy  I am with Sartography and we just released Version 1.0 and would be happy to share with you how we are handling BPMN.IO integration with Formly if you are still interested.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
