### ISSUE TITLE
Interesting BPMN / Camunda Modeller / OpenAPI article

### ISSUE THREAD

**Issue by CapnKernel** [sartography/SpiffWorkflow#110]
In the absense of us having a mailing list, I'm putting it here.

  https://medium.com/@tom.larkworthy/automating-automation-bpmn-openapi-futurice-2d80811b4bcb

**Comment by calexh-sar** [comment]
@CapnKernel  I am with Sartography and we just released [Version 1.0](https://github.com/sartography/SpiffWorkflow/releases/tag/1.0) in case you are still interested in SpiffWorkflow.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
