### ISSUE TITLE
how to deal the input data, output data

### ISSUE THREAD

**Issue by szx1234** [sartography/SpiffWorkflow#111]

**Comment by martinr1604** [comment]
Ich kehre zurück am 11.09.2020.




Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht
"[knipknap/SpiffWorkflow] how to deal the input data, output data (#111)"
gesendet am 01.09.2020 14:19:16.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by calexh-sar** [comment]
@szx1234 I am with Sartography and we just released [Version 1.0](https://github.com/sartography/SpiffWorkflow/releases/tag/1.0) and would be happy to share with you how we are handling input and output data if you are still interested.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
