### ISSUE TITLE
How to use Input and Output Parameters?

### ISSUE THREAD

**Issue by cheoppy** [sartography/SpiffWorkflow#128]
Both Camunda and bpmn.io with the properties panel extension support of defining Input and Output parameters for each task. I'm trying to set up a workflow where some specific info about a task is in either the Input or the Output parameter, but I can't find a way to read (or write) these fields in SpiffWorkflow. 

I tried to look at how Task.get_data and Task.dump() works, but couldn't find any hint about the Input/Output parameters. 

Are these parameters defined at the tasks supported? If so, how can they be accessed? Thanks a lot!

**Comment by danfunk** [comment]
Task data is ALWAYS passed along.  Whatever the data is when the task completes, that is what is handed off to the next task.  So any information a Task may need as input, must have been defined by a previous task.  Input is always what was completed previously, output is always the data after the task completed.  If  the tasks are parallel, then they each receive the same task data from the gateway, and their collective data is merged together when the gateway closes.   

While we did do a little work to support some of the Camunda specific extensions (specifically form definitions), it isn't the goal of Spiff Workflow to support the camunda namespace.  We are driving towards a design where we can support any custom extensions, particularly for handing User Tasks.  As for the Input and Output parameters, we aren't using them, and have no plan to do so.

**Comment by cheoppy** [comment]
Thanks for the info! I think I'll then use Spiff Workflow to execute the workflows and may add some .bpmn file parsing to read the Camunda extensions when needed.
