### ISSUE TITLE
Gateway Exception in Scripting Enhancements

### ISSUE THREAD

**Issue by AndreAmorim** [sartography/SpiffWorkflow#140]
What is the correct way to get a return from a script and assign it to a variable in the stream?
I have been successful in assigning the return of a function to a variable using a Script Task (spam = my_function(), in an inline Script) however the process fails when I check spam!="yes" on a gateway getting the following exception: ..."SpiffWorkflow\bpmn\PythonScriptEngine.py", line 123, in validateExpression
     raise Exception("error parsing expression "+text + " " +
TypeError: can only concatenate str (not "Task") to str"

**Comment by danfunk** [comment]
Well, it's a lousy error message, looking like it is erroring out trying to even create the error message in this case.  I will definitely fix this.

Were I to guess, I would say that my_fuction() is not returning "yes" or "no", it seems to be returning some sort of object.  I've tried to reproduce this locally, but I can't seem to do so.  If your function is returning a string, there is no reason why this wouldn't work. 

This works fine, for example: 
![example_spam](https://user-images.githubusercontent.com/515662/140167651-f3076967-a236-4388-9676-c0ca3cf597b8.png)

**Comment by danfunk** [comment]
It just occurred to me that we have some recent changes in the master branch around the PythonExpressionEngine that are not yet released.  Perhaps use the master branch from git as a dependency, and see if that fixes the problem?  Will try to get a release out shortly,  we have a few other fixes that need to go out as well.
Using pipenv, your dependency would be:
spiffworkflow = {git = "https://github.com/sartography/SpiffWorkflow"}

**Comment by danfunk** [comment]
Scratch that, I went ahead and released all the outstanding changes,  would like to see what error message if any you get back after you update to the latest release (1.1)
