### ISSUE TITLE
Access task variable in script task

### ISSUE THREAD

**Issue by asalmoqbel** [sartography/SpiffWorkflow#142]
Hi,

I have a script task where I want to access the context of the process itself, I mean the `task` variable, I have noticed that it has been commented out here:
https://github.com/sartography/SpiffWorkflow/blob/master/SpiffWorkflow/bpmn/PythonScriptEngine.py#L262
```python
        # data.update({'task':task}) # one of our legacy tests is looking at task.
        # this may cause a problem down the road if we
        # actually have a variable named 'task'
```
is there any plan to fix that issue and uncomment that line ?

BR,

**Comment by danfunk** [comment]
We did not like altering the task.data, as we believe that should be owned by the BPMN/end user.  We shouldn't jam other stuff in there that wasn't explicitly asked for.

If you want your script to have access to the task, extend the PythonScriptEngine, and add task to the globals.  That is basically what we do when using the library for other projects.

**Comment by asalmoqbel** [comment]
fair enough, thanks @danfunk for your answer and I do like the approach to keep this library as simple as possible and relay on user implementation to extend it.
