### ISSUE TITLE
Drop camunda attributes on Events

### ISSUE THREAD

**Issue by danfunk** [sartography/SpiffWorkflow#158]
Our core BPMN code currently references camunda attributes for some aspects of events.  Specifically Expression and ResultVariable.   We should not have direct dependencies on these attributes.  We could add support for them through the CamundaParser, but no reference to the Camunda namespace should exist in the core BPMN classes and methods. 

We want to create and maintain the oppertunity to evolve our own definition of variable scopes and data handling that will strive to be more in line with the BPMN 2.0 standard, and when not defined there, as pythonic as possible, and in keeping with the scoping of variables that is inherent in python programming.

**Comment by essweine** [comment]
Camunda specific messaging and multi instance extensions are now handled by the camunda parser and there are no remaining references in the main parser.
