### ISSUE TITLE
ValueError: (<Task object (Start) in state FUTURE at 0x247c3392970>, '_add_child() requires a TaskSpec')

### ISSUE THREAD

**Issue by madayt** [sartography/SpiffWorkflow#161]
![image](https://user-images.githubusercontent.com/42445813/155681741-567178d1-906f-48a6-9ee5-406475cdcbfa.png)
![image](https://user-images.githubusercontent.com/42445813/155681782-8c23571d-9cff-4dbe-934f-f2ce13b27d6b.png)
![image](https://user-images.githubusercontent.com/42445813/155681836-efefe63e-75a3-44d9-9546-ac9b336a77c8.png)

**Comment by danfunk** [comment]
Hi Madayt, were you able to resolve your issue?
