### ISSUE TITLE
What happened to 1.1.4?

### ISSUE THREAD

**Issue by HoneyryderChuck** [sartography/SpiffWorkflow#171]
Hi 👋 

We recently upgraded spiff from 1.1.4 to 1.1.5, and noticed a crash in the deserialization process immediately afterwards, exactly on [this line](https://github.com/sartography/SpiffWorkflow/blob/v1.1.5/SpiffWorkflow/serializer/dict.py#L888). After inspecting the serialized state we store, we noticed that "workflow_name" is not present in the task tree payload.

Inspecting the releases list, I also noticed that 1.1.4 release notes were removed, and I assume it got yanked from PyPI. Was there a regression that caused this problem, which motivated the version yank? And if so, why wasn't it announced in the 1.1.5 release?

EDIT: also found [this MR](https://github.com/sartography/SpiffWorkflow/pull/160). Assuming this has been fixed, when can we expect a fix release?

**Comment by danfunk** [comment]
Hi Tiago, you caught me in a slew of mistakes as I was rushing to get a beta release prepared for a client.   Let me address your concerns, and ask for you help in getting this resolved.

1. [Version 1.1.4 is still available on PyPi](https://pypi.org/project/SpiffWorkflow/1.1.4/).  When we created that release we were moving to GitHub's actions to handle automatic deployments and we made some mistakes.  The 1.1.4 version of SpiffWorkflow was not properly tagged.   I am sorry for any inconvenience this caused, and I believe things are well documented and should run smoothly going forward.

2. We now have a bug in our serialization code that may prevent people who upgrade from de-serializing their workflows.  I didn't realize this at the time of the release.  This error was introduced in the merge you mentioned in your final "EDIT" paragraph, and that merge includes the line you mention specifically in your first paragraph.  I will get a pull request out this morning to resolve this issue.  I would appreciate if you could give it a try, as I don't have any workflows that would still exhibit this problem.

Yours faithfully,

Dan

**Comment by danfunk** [comment]
@HoneyryderChuck  - please check out pull request #172

**Comment by HoneyryderChuck** [comment]
@danfunk thx for the reply! No worries, thought initially it was a breaking change in a patch release, but glad to know (not so glad, lol 😂 ) that it's just a bug, mistakes happen. 

Will give it a test-drive for sure, if not today, then tomorrow. 👍

**Comment by HoneyryderChuck** [comment]
patch tested locally and acknowledged, it fixed the bug 👍

**Comment by danfunk** [comment]
v.1.1.6 contains the fix.
