### ISSUE TITLE
Code decoupling advice: move TaskState object out of Task object.

### ISSUE THREAD

**Issue by a358003542** [sartography/SpiffWorkflow#176]
If we move the task state out of Task object, then the whole project reference the Task object is only five-seven counts.  There are so many reference[about one hundred references ] to Task object just use the taskstate object, it is just a emun constant object. 

If we doing this decopling work, then this project code would be more anti-bugs. and by the way some others maybe customize the Task and the Workflow object, like put the on-fly state to database, but they really not need to change this constant definitions. 

```
from enum import IntFlag

class TaskState(IntFlag):
    MAYBE = 1
    LIKELY = 2
    FUTURE = 4
    WAITING = 8
    READY = 16
    COMPLETED = 32
    CANCELLED = 64

    FINISHED_MASK = CANCELLED | COMPLETED
    DEFINITE_MASK = FUTURE | WAITING | READY | FINISHED_MASK
    PREDICTED_MASK = FUTURE | LIKELY | MAYBE
    NOT_FINISHED_MASK = PREDICTED_MASK | WAITING | READY
    ANY_MASK = FINISHED_MASK | NOT_FINISHED_MASK


TaskStateNames = {TaskState.FUTURE: 'FUTURE',
                  TaskState.WAITING: 'WAITING',
                  TaskState.READY: 'READY',
                  TaskState.CANCELLED: 'CANCELLED',
                  TaskState.COMPLETED: 'COMPLETED',
                  TaskState.LIKELY: 'LIKELY',
                  TaskState.MAYBE: 'MAYBE'}

```

**Comment by danfunk** [comment]
I agree with you.  Can you submit this as a pull request?

**Comment by a358003542** [comment]
@danfunk Sure, but i will submit in this week's Saturday.

**Comment by a358003542** [comment]
@danfunk hi danfunk. I have create a submit.

**Comment by danfunk** [comment]
pull request merged.
