### ISSUE TITLE
1.1.7 contains breaking changes

### ISSUE THREAD

**Issue by HoneyryderChuck** [sartography/SpiffWorkflow#182]
Hi 👋  I've tested the upgrade to teh latest version, and it seems that some variables were moved around, specifically `TaskStates`.  The code in question breaks because it relies on available of constants when having tasks, so there's a lot of `task.WAITING` and the like.

Would you reconsider reverting this? Even if we would redo the code, It seems a bit of overhead for no real gain, i.e. now I have to `import TaskStates` in order to access the state static variables.

**Comment by danfunk** [comment]
Hi @HoneyryderChuck , I see now that this is a breaking change, if you had code that was referencing these states on a instance variable, such is the case with "task.WAITING".  I did assure before commiting the pull request that the method Task.WAITING (at the class level) is not broken, but rather [deprecated](https://github.com/sartography/SpiffWorkflow/blob/main/SpiffWorkflow/task.py#L119).  

You should find that it is perfectly possible to change your methods from task.WAITING to Task.WAITING and things will work fine without adding additional imports - and this should prove a very minor change. 

I am hesitant to reintroduce the ability to refer to task.WAITING and the like, because it's somewhat error prone, as pointed out in several of the top answers [here](https://stackoverflow.com/questions/68645/static-class-variables-and-methods-in-python)

As to why this change was put in place, please see [Issue 176](https://github.com/sartography/SpiffWorkflow/issues/176) for reference.

If you still feel strongly about this, I'm happy to listen to a counter argument.

**Comment by HoneyryderChuck** [comment]
If I understood the reference links well, it's about the whole "calling an instance property falls back to the class property and we should avoid this", right? 

I agree that this should be something to avoid in most cases, particularly with "downcased" properties, which are implicitly understood as "instance properties". However, I'd make the case that "upcased" properties are different, given that they're implicitly understood as static variables, and therefore not expected to be changed during the course of a program.

Of course, these are "informal" contracts, and anything can happen in python, of which I'm not a big expert on all the long tail issues. But still, I think that an exception to this rule could be made for "upcased" class properties.

Bear in mind that, in order to adapt my code to this change, I'll have to `from SpiffWorkflow.specs.base import TaskStates` everywhere, which is quite the change considering the many places we're using this indirect access; which means, from my perspective, like a lot of overhead work (and effectively a breaking change), for very little tangible benefit (as per my point above "downcased vs upcased").

Let me know what you think. You probably have more XP in python, and can help me understand other edge cases being addressed with this change (which I'd still consider for at least a minor version bump :) ).

**Comment by danfunk** [comment]
I hear you, but I feel like an important point got lost, This is still valid (albeit deprecated):
```
from SpiffWorkflow import Task
print(Task.WAITING)
```
So if you are using the Task object, just reference directly from the class, not from an instance of the class. Generally speaking I don't think this would require an additional import.

This is a genuine offer - if you would like @burnettk could write you a bash script that would do a find a replace in your code, and assure the import statement was there, and get your code cleaned up in a jiffy if you need help.

**Comment by HoneyryderChuck** [comment]
The suggestion is valid if I'm already importing the Task, but that's not the case in the vast majority of places (in my case), where I have a bucket of functions where tasks are received as input. And as you pointed out, even that's deprecated, so I'd have to prepare for the change.

All in all, I don't consider this a net positive, and a breaking change (don't know whether this type of access patterns are considered as "public API" in python), based on the upcase/downcase dychotomy. But that's just my opinion, so I'll respect it if you think otherwise :)

**Comment by danfunk** [comment]
@HoneyryderChuck  
I am sorry you feel this is an unnecessary change.  It does provide benefits that after careful consideration and discussion we consider to be valid.  I've tried to deprecate what we consider to be the standard use of these constants.  

I can offer you these options:
1) if you would like to submit a pull request that will (a) allow instance variable use while (b) ALSO warning that such use is deprecated, I will accept the request and get out an immediate release.  
2) We can pair up with you and have a look at the code and see if we can write a quick script that will clean up your code so you can move forward efficiently.

**Comment by HoneyryderChuck** [comment]
No worries, thx anyway for hearing my arguments, appreciate it. I admit that this might be a bit "IMO", as I'm not sure what's the python community stance on whether accessing class variables via instance is considered "acceptable usage and public API" or rather "accidental behaviour", so I'm definitely fine with "agree on disagreeing" here.

I'll try to do smth about trying 1. based on the patch you linked to. I'm still investigating other bugs (some resulted in the other open issues), so I'll work on that once I'm done with the rest.
