### ISSUE TITLE
feature requests: LoopResetTask support conditional exit

### ISSUE THREAD

**Issue by HoneyryderChuck** [sartography/SpiffWorkflow#183]
Hi 👋  I've been lately working with the `LoopResetTask`. It is my understanding that this loop can't be broken, which makes it a bit less "valuable", at least for our use case. When looking at the [structured loop pattern](http://www.workflowpatterns.com/patterns/control/new/wcp21.php), there's also a reference to a cond. Would you be open to the feature? I can share the patch that made it work (at least for now).

**Comment by danfunk** [comment]
There are certainly ways to conditionally loop back to a previous point, but that is not the intent of the LoopResetTask - which was not intended to be used directly - it is an optimization to better handle recursive structures in BPMN.

I get the impression that you are manually building out the workflows in code, rather than using a diagram to drive the process.  I don't fully understand your use case at the moment.  One way that I would handle a structured loop pattern would be with a gateway:

![image](https://user-images.githubusercontent.com/515662/170110786-a8c96fc6-e9b2-4d9b-8b66-1c68cf264770.png)

**Comment by HoneyryderChuck** [comment]
You're right, I'm not using diagrams, rather json/dict integration, so the BPMN layer is absent from my use case (which probably means, no gateway). I was looking more for a "structured loop with condition" under `SpiffWorkflow.specs`, as that seems to be where the more "raw" implementation of workflow patterns is, hence the question.

**Comment by essweine** [comment]
If I can step in here -- the gateway in the above diagram is equivalent to a Spiff `ExclusiveChoice` task, which you could use to break out a a loop.  The `LoopResetTask` isn't intended to be used directly; it is an optimization that was introduced to reuse tasks when loops are detected.  You would create a workflow as in this simple example:
```
from SpiffWorkflow.specs import WorkflowSpec, Simple, ExclusiveChoice
from SpiffWorkflow.operators import Attrib, Equal
from SpiffWorkflow import Workflow
from SpiffWorkflow.task import TaskState

spec = WorkflowSpec('Loop Test')
task = Simple(spec, 'Do Work')
gw = ExclusiveChoice(spec, 'Done?')
end = Simple(spec, 'Done!')

cond = Equal(Attrib('done'), True)

spec.start.connect(task)
task.connect(gw)
gw.connect(task)
gw.connect_if(cond, end)

wf = Workflow(spec)

counter = 0
while not wf.is_completed():
    ready = wf.get_tasks(TaskState.READY)
    if len(ready) > 0 and ready[0].task_spec == task:
        if counter > 2:
            ready[0].update_data({'done': True})
        counter += 1
    wf.complete_next()

print("done")
```
The loop reset task would get inserted automatically between the gateway and the return to 'Do Work', but the gateway would control breaking out of the loop.

**Comment by HoneyryderChuck** [comment]
@essweine thanks for the suggestion. Isn't the outcome of that an invalid workflow, considering that calling `.validate` on it would figure an infinite loop, due to task being both a parent and a child of `gw`?

**Comment by essweine** [comment]
It is true that the validate function will fail.  That doesn't have anything to do with the loop reset task though (it isn't even in the workflow at that point, it gets inserted at runtime).  Officially, Spiff doesn't support this pattern (Structured Loop, #21 in the list of supported patterns at https://spiffworkflow.readthedocs.io/en/latest/non-bpmn/patterns.html), and there isn't a dedicated task type for it, though it can be nonetheless be done, if not validated.
