### ISSUE TITLE
并行网关都是FUTURE 状态吗， 我该如何改成READY让他去执行呢

### ISSUE THREAD

**Issue by ghost** [sartography/SpiffWorkflow#194]
并行网关都是FUTURE 状态吗， 我该如何改成READY让他去执行呢

**Comment by danfunk** [comment]
`do_engine_steps()`
will execute all tasks that are not manual / user tasks.


![image](https://user-images.githubusercontent.com/515662/179547300-191faf7d-71ce-4411-82b5-04d46e6fc74f.png)
