### ISSUE TITLE
Gateway Task Problem

### ISSUE THREAD

**Issue by ghost** [sartography/SpiffWorkflow#200]
The task behind the gateway is missing. What are the limitations of the gateway task?

**Comment by danfunk** [comment]
Hi @dongxinlong66,

I am not certain what you mean.  Can you please provide a detailed description of the problem.  A code example, and BPMN diagram would be helpful in trying to debug and understand your issue.

Dan

**Comment by ghost** [comment]
I fixed this myself, this is my problem, I recently made a reject feature, but when I change the status from COMPLETED to READY, I get an error: "Activity_1mxiqpw: State went from COMPLETED to READY!"

How do I change my status

**Comment by danfunk** [comment]
You should not manually change the status of a task.  It would help to see the BPMN diagram you are executing.   Maybe you want to use something like a [cancel event](https://spiffworkflow.readthedocs.io/en/latest/bpmn/events.html?highlight=cancel#cancel-events)?
