### ISSUE TITLE
Data Objects not correctly parsed in to_dict of default BPMN serializer

### ISSUE THREAD

**Issue by sharky98** [sartography/SpiffWorkflow#218]
Hello,

I think I found a bug in the following method.

https://github.com/sartography/SpiffWorkflow/blob/776b2724255a51f9cb9497ff922768fdc80b03da/SpiffWorkflow/bpmn/serializer/workflow_spec_converter.py#L107-L127

The data object object should be like this to be serialized. At least in the object I am getting back from the workflow.

```python
"data_objects": [(obj, self.convert(spec.data_objects[obj])) for obj in spec.data_objects],
```

**Comment by essweine** [comment]
Yes, this is a bug.  I am aware or if and am working it.  We should have a fix soon.

**Comment by essweine** [comment]
We've merged a fix for this into main.
