### ISSUE TITLE
BPMN parser only finds the first specified extension

### ISSUE THREAD

**Issue by dickkniep** [sartography/SpiffWorkflow#254]
When more than one extensions is entered for a script task in Camunda. Spiff only finds the first.

![Schermopname (2)](https://user-images.githubusercontent.com/409767/196690075-64b6c03e-a9ee-4fb4-b53b-aef044f2c2cb.png)

Here Spiff will only find the first `callback`

**Comment by essweine** [comment]
I am not able to replicate this.  Would you mind attaching the XML that was generated for this task?

**Comment by dickkniep** [comment]
<bpmn:scriptTask id="Activity_0dzopus" name="Voorbereiding">
      <bpmn:extensionElements>
        <camunda:properties>
          <camunda:property name="collector_workflow" value="wob1" />
          <camunda:property name="callback" value="polling" />
        </camunda:properties>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_0tzbpia</bpmn:incoming>
      <bpmn:outgoing>Flow_14lwhpu</bpmn:outgoing>
      <bpmn:script>ProcessTaskSynchronous.sync_exec</bpmn:script>

**Comment by dickkniep** [comment]
This is part of the bpmn that I use. It has been produced by camunda version 5.3.0. I use the following code in Python to retrieve the parameters:

` def bld_extensions_parms(task) -> dict:
        """
        Routine builds a copy of the config parameters read from Camunda and prepares them for passing to the module
        Note that these parameters are read-only (therefor they are copied from the task_spec)

        :param task:
        :return: dict with configuration values
        """
        config = copy(task.task_spec.extensions)
        if len(config):
            return {'extensions': config}
        else:
            return {}
`

**Comment by essweine** [comment]
Thank you.  I'll take a look at this soon.  Thanks for including the Camunda version, as I suspect that this is a factor.

**Comment by dickkniep** [comment]
After extra testing it seems this was a one time glitch. Now all seems to work properly. So I am closing this issue while apologizing for bothering you.....

**Comment by danfunk** [comment]
Good to hear.
