### ISSUE TITLE
subProcess not get recognized in 1.2.1

### ISSUE THREAD

**Issue by george-0-huang** [sartography/SpiffWorkflow#279]
**Issue: subProcess is not parsed correctly from bpmn file** 

The attached file is a simple bpmn  (one subprocess with one task inside it , renamed to txt to workaround github attachment restriction) generated from bpmn.io online editor:
[test2.txt](https://github.com/sartography/SpiffWorkflow/files/10365257/test2.txt)

Here is the the snapshot of the subclass spec from above bpmn
```
    <subProcess id="Activity_0soryhi" name="Goal">
      <incoming>Flow_1tkt88y</incoming>
      <outgoing>Flow_1hoznin</outgoing>
```

reporting following error  with 1.2.1, because the above subProcess did not get recognized and imported into workflow.subprocess_specs ...not know why , or this is a known issue?

```
  File "/Users/georgehuang/Documents/VsCode/shepherd/venv/lib/python3.7/site-packages/SpiffWorkflow/bpmn/workflow.py", line 84, in create_subprocess
    workflow.subprocess_specs[spec_name], name=name,
KeyError: 'Activity_0soryhi'
```
which was working fine with 1.1.7

**Debug Findings**
1: workflow.subprocess_specs is empty
2: workflow.subprocesses is empty

**Comment by essweine** [comment]
After making a slight change (add a script to the script task -- setting `done = True`) I was able to run your workflow using our example application:

`./run.py -p Process_1 -b test2.bpmn`

With the output:
```
Workflow Data
{
  "done": true
}
```
So it seems to be getting executed.  Can you provide more details?

**Comment by george-0-huang** [comment]
**Updates:**
1:  Confirmed your result: bpmn from 1.1.7,  does works with latest wrapper code from https://github.com/sartography
[spiff-example-cli](https://github.com/sartography/spiff-example-cli)
2: When runs it with the wrapper code as it was a few month, then it manifest the issue

**Conclusion,**
we need to update the wrapper code to support 1.2.1  

I was expecting the lib's API is backward compatible, but I can understand ....  thanks for the support

**Note**
This is extra code need for 1.2.1 in parse function

```
    top_level = parser.get_spec(process)
    if load_all:
        subprocesses = parser.find_all_specs()
    else:
        subprocesses = parser.get_subprocess_specs(process)
   return BpmnWorkflow(top_level, subprocesses, script_engine=CustomScriptEngine)
```
