### ISSUE TITLE
Very first time start failed

### ISSUE THREAD

**Issue by vkuehn** [sartography/SpiffWorkflow#290]
Just follwing the instructions on the home page for the docker compose approach and it looks like this for me

docker compose up -d
[+] Running 4/5
 ⠿ Network spiffworkflow_default      Created                                                                                0.1s
 ⠿ Container spiffworkflow-db         Healthy                                                                               31.6s
 ⠿ Container spiffworkflow-connector  Started                                                                                1.1s
 ⠿ Container spiffworkflow-backend    Error                                                                                 33.9s
 ⠿ Container spiffworkflow-frontend   Created                                                                                0.1s
dependency failed to start: container spiffworkflow-backend exited (1)

docker compose version is latest release 2.16.0
any idea why that could be ?
anything I can do about that  ?

**Comment by danfunk** [comment]
I'm seeing the same error, working on it now.

**Comment by danfunk** [comment]
@vkuehn  - thank you so much for pointing out the issue.  There was error in a recent change to our configuration files - if you re-download the docker file:
```
wget https://raw.githubusercontent.com/sartography/spiff-arena/main/docker-compose.yml -outfile docker-compose.yml
```

-- OR fix the line in the file that sets the backend environment so that it reads:
```
 SPIFFWORKFLOW_BACKEND_ENV: "local_development"
````

Everything should work.  So sorry for this issue and thank you again for bringing it to our attention.

**Comment by vkuehn** [comment]
@danfunk  thanks a lot for the very fast Response.

I can confirm that solved the issued.
