### ISSUE TITLE
does this package support python2.7

### ISSUE THREAD

**Issue by HellenWang** [sartography/SpiffWorkflow#304]
because of some historical reasons，our project is build with python2.7, I want to know does it works in python2.7 env? 
could I download wheel package at [pypi](https://pypi.org/project/SpiffWorkflow/#files) and use it at python2.7 env?

**Comment by danfunk** [comment]
Hi @HellenWang,  Earlier versions such as https://pypi.org/project/SpiffWorkflow/0.5.22/ work with python 2.7 - we abandoned python 2 when we released version 1.0.  We can't offer much in the way of support I'm afraid.

**Comment by HellenWang** [comment]
> 

gotcha, thank you
