### ISSUE TITLE
Implementation of try/catch from custom tasks in v2.0

### ISSUE THREAD

**Issue by asauve2** [sartography/SpiffWorkflow#335]
Following the discussion in #334 I post here a code snippet to introduce a way to implement the following 
pseudo code:

```
try:
    something
except:
   run alternate task branch
```

This is not really an issue in the current v2.0.0rc0 branch, 
but more likely to start the discussion on this topic.

Depending on the use case, boundary events can be used from workflow side 
or programatically from code side. 
We are in the second case as we have a single `ServiceTask` parametrized with an attribute
`class` indicating the algorithmic code to execute by the task.
When an error occurs we want to rediret the task flow to a dedicated error handling branch
which is known from workflow side but the `bpmn_id` of the branching event is not explicitely
known to the `ServiceTask`.

The minimal workflow example is copied below for visual support:

![boundary-error](https://github.com/sartography/SpiffWorkflow/assets/134524773/1a425c89-d398-4e31-aa61-9b55a02ebd62)

We do not have git access from our private network so instead of a push request here is 
an explicit implementation to provide the functionality.
This example can also serve as a basis for a smooth transition from current BoundaryEvent implementation
to a new one.

The snipets code below is tested and functional with v2.0.0rc0:
```
from SpiffWorkflow.bpmn.specs.control                import _BoundaryEventParent, BoundaryEvent
from SpiffWorkflow.bpmn.specs.event_definitions      import ErrorEventDefinition

class BoundaryEventAwareTaskSpec:
   def get_boundary_event_tasks(self, my_task):
        """Returns the list of boundary event tasks attached to my_task
        """
        for input_spec in self.inputs:
            if isinstance(input_spec, _BoundaryEventParent):
                # the boundary parent contain the current task spec plus 
                # boundary events
                for event_spec in input_spec.outputs:
                    if isinstance(event_spec, BoundaryEvent):
                        # check if event Task are already defined (not the case in SpiffWorkflow-1.2)
                        return my_task.workflow.get_tasks_from_spec_name(event_spec.name)

        # no boundary events found
        return tuple()

    def triggerIntermediateBoundaryError(self, my_task, exception):
        """Triggers the execution of tasks attached to an Interrupting Error Boundary Event
        **if and only if one is attached to current task**.

        Returns
        -------
        - True if an event was found and propagated to workflow execution
        - False otherwise (requiring explicit error handling)
        """
        for event_task in self.get_boundary_event_tasks(my_task):
            if isinstance(event_task.task_spec.event_definition, ErrorEventDefinition):
                error_event = ErrorEventDefinition(
                    event_task.task_spec.bpmn_id, 
                    # error_code is a string and should be usable for messages
                    error_code=str(exception))
                my_task.workflow.catch(error_event)
                return True
        return False


class CustomTaskSpec(BpmnSpecMixin, BoundaryEventAwareTaskSpec):
    def _run_hook(self, my_task):

        # the following try/catch block uses the features above to trigger the 
        # boundary error event without knowledge of bpmn_id 
        try:
            # custom code that may fail
        except Exception as e:
            if self.triggerIntermediateBoundaryError(my_task, e):
                # False required for normal error event processing in spiff v2.0.0rc0
                return False
            else:
                raise e  # no error handler found => let error go upward
```

Would that fit in v2 branch or does it break expected usage?

**Comment by asauve2** [comment]
This comment is a follow-up as the code stated above has to be adapted to changes that occured 2 month ago on the unstable branch which is not released yet.

The current BPMN ErrorEvent triggering was simplified and semantics are now more consistent thanks to @essweine refactoring.

```
# 2023-08-28 master branch (i.e version > 2.0.1 )
try:
    # something that fails
except:
        for event_task in self.getBoundaryEventTasks(my_task):
            if isinstance(event_task.task_spec.event_definition, ErrorEventDefinition):
                # Note here that the error spec *throws*
                event_task.task_spec.event_definition.throw(my_task)
 ```

The `getBoundaryEvent()` method is custom user code as in the use case here
boundary events presence are not *a priory* known from the task.

**Comment by essweine** [comment]
Appreciate the update.  Your code examples will be helpful to anyone implementing custom tasks.
