### ISSUE TITLE
Spiffworkflow Library - State Transitions

### ISSUE THREAD

**Issue by danfunk** [sartography/SpiffWorkflow#363]
SpiffWorkflow has the ability to execute callback functions on certain events.  This allows library users to automatically execute actions whenever changes are made to tasks.  This functionality would be more useful if these events lined up cleanly with state transitions of tasks.

**Comment by danfunk** [comment]
@essweine is this still relevant?

**Comment by essweine** [comment]
Better callback functionality would allow some performance improvements to be made.

**Comment by essweine** [comment]
Resolved with https://github.com/sartography/SpiffWorkflow/pull/408
