### ISSUE TITLE
Cycle timer child task doesn't inherit parent task data

### ISSUE THREAD

**Issue by yyscamper** [sartography/SpiffWorkflow#368]
I have designed a manual task with boundary cycle timer event, when event fires, a specified script task will  be executed. I found the script task does not inherit the data of its parent.

I figure out the root cause is likely to be here: https://github.com/sartography/SpiffWorkflow/blob/main/SpiffWorkflow/bpmn/specs/mixins/events/event_types.py#L63 , when cycle timer fires, a new child task will be created, it becomes ready state and skip the _update_hook, thus the task data will not be inherited.

My expectation is cycler timer triggered event can also inherit parent task data just like all other tasks.

**Comment by yyscamper** [comment]
the data object reference is also not handled

**Comment by essweine** [comment]
> the data object reference is also not handled

Data object copy is part of the update process.
