### ISSUE TITLE
Comparing pickles in tests depends on implementation-specific details and is unreliable

### ISSUE THREAD

**Issue by daxtens** [sartography/SpiffWorkflow#38]
For fun I ran the test suite on PyPy. It all works, up till the point where it compares two pickles:

Exception: task_specs/go_to_repetition/pre_assign/[0]/Unequal: 'gAJjU3BpZmZXb3JrZmxvdy5vcGVyYXRvcnMKQXNzaWduCnEAKYFxAX1xAihVBXJpZ2h0cQNYAQAAADBxBFUPcmlnaHRfYXR0cmlidXRlcQVOVQ5sZWZ0X2F0dHJpYnV0ZXEGWAYAAAByZXBlYXRxB3ViLg==' vs 'gAJjU3BpZmZXb3JrZmxvdy5vcGVyYXRvcnMKQXNzaWduCnEAKYFxAX1xAihVDmxlZnRfYXR0cmlidXRlcQNYBgAAAHJlcGVhdHEEVQVyaWdodHEFWAEAAAAwcQZVD3JpZ2h0X2F0dHJpYnV0ZXEHTnViLg=='

If you base64 decode the string, you see that the pickles are the same, just that they have keys in a different order.

I initially thought this was a PyPy bug and reported it: https://bugs.pypy.org/issue1693
**However, it turns out that even in regular python it's not safe to rely on the ordering.**

I'm not sure what the best way to fix this is. 
- At DigiACTive we're trying to move away from pickles entirely - see the [PureDictionarySerializer branch](https://github.com/DigiACTive/SpiffWorkflow/compare/feature;PureDictionarySerializer) (it's not quite ready for a pull request yet but I'll get there eventually) - one option would be to go with that and just do away with comparing pickles entirely. 
- Another option is to rewrite the tests to unpickle the objects and compare them - that would require writing some `__eq__` functions for Assign, etc.

I don't understand the rationale for pickling things, so I'd lean towards the first solution, but I'm fully open to being convinced about the necessity of pickles.

**Comment by knipknap** [comment]
We used pickling simply because it was easy. I don't necessarily recommend this in the real world, because it also make debugging rather inconvenient. Nonetheless, the test should probably just use a better mechanism for comparing the pickles.

**Comment by Muzikbrat** [comment]
hello,
Will your library help in modelling a cause-effect workflow?

**Comment by Muzikbrat** [comment]
hi,
Can you please clarify whether actual actions can be connected to the tasks. Actions here means python processing functions which would work on data passed through the workflow. If yes, can you explain how, or give a sample code.
Thanks

**Comment by knipknap** [comment]
Please don't use this bug for asking questions. Feel free to open your own support issues.

**Comment by knipknap** [comment]
I'd be curious if this bug still happens after the latest serializer refactoring. Could you test this again?

**Comment by knipknap** [comment]
Please feel free to reopen if the problem persists.
