### ISSUE TITLE
Type in the releast notes.

### ISSUE THREAD

**Issue by pilayar76** [sartography/SpiffWorkflow#391]
Other changes section has a typo in Rremoved.

![image](https://github.com/sartography/SpiffWorkflow/assets/32598510/e82dfccc-7b42-4c02-9cbb-412b3c53be0a)

**Comment by essweine** [comment]
Corrected in https://github.com/sartography/SpiffWorkflow/commit/cdf7fc46d2e00f213d296b9055cf2e17bde2e1dc
