### ISSUE TITLE
Process Instance Migration: Find all completed tasks in a Process Instance

### ISSUE THREAD

**Issue by danfunk** [sartography/SpiffWorkflow#416]
Calculate which tasks were executed in a process instance (climb back up the tree) and compare these to what has changed between two process models to determine if it is possible to safely migrate the process instance to the new model.

**Comment by essweine** [comment]
https://github.com/sartography/SpiffWorkflow/pull/422 introduced new utilities for comparing workflow specs and identifying tasks in a workflow with changed specs but I think this requires more discussion.  I'm not sure that making such a decision really makes sense as part of the library; I think it might be too context dependent to really be able to do it here.

**Comment by calexh-sar** [comment]
Completed, will be QA'd as part of the finished process.
