### ISSUE TITLE
Process Instance Migration: Update the process instance with a new model

### ISSUE THREAD

**Issue by danfunk** [sartography/SpiffWorkflow#417]
Migrate a process instance to a new model - ideally while preserving the Task GUID so that any history information gathered about the process instance is still valid and accurate.  

IMPORTANT:  The Dev Day Estimate here is just a guess by Dan to help establish a rough idea of the work involved on this task.

**Comment by burnettk** [comment]
hammered in https://github.com/sartography/SpiffWorkflow/pull/426

**Comment by essweine** [comment]
Resolved in https://github.com/sartography/SpiffWorkflow/pull/426
