### ISSUE TITLE
Make a release on PyPi

### ISSUE THREAD

**Issue by dee42** [sartography/SpiffWorkflow#43]
The latest release on PyPi was 0.3.0 in 2009.  The code has changed a fair amount since then.  It's time for a new version number - 1.0 maybe? - and a new release.

**Comment by dee42** [comment]
If @matthewhampton or I were given admin rights on the PyPi page, we'd be happy to do the work here.

**Comment by knipknap** [comment]
I added user "matthewhampton" as a maintainer on PyPi. If you let me know your username, I can add you as well.

**Comment by dee42** [comment]
dave42moore.  Thanks

**Comment by dee42** [comment]
Any preference what we should bump the version number to?

**Comment by knipknap** [comment]
Personally, I would have released a 1.0 version after #13 is fixed. Some of the TaskSpec API will definitly break during the cleanup.

**Comment by dee42** [comment]
Okay, so 0.4 then?

**Comment by knipknap** [comment]
Sounds cool to me. If you are feeling confident and prefer a higher number, all is fine with me.

**Comment by dee42** [comment]
Done

**Comment by knipknap** [comment]
Awesome, thanks!
