### ISSUE TITLE
doubt on tasks

### ISSUE THREAD

**Issue by Muzikbrat** [sartography/SpiffWorkflow#50]
Hello,
How would one connect a python function to a task, for example in workflow1.py?
Or how would one get the task to do some processing ?

**Comment by knipknap** [comment]
I just committed a tutorial in 18ccb45391bd74f3eb209efe58c93596f1a9099c. Does this answer your question?

The tutorial is here:
http://spiffworkflow.readthedocs.io/en/latest/tutorial/tutorial.html
