### ISSUE TITLE
Run all non manual tasks

### ISSUE THREAD

**Issue by jayste** [sartography/SpiffWorkflow#52]
From the tutorial:
```
# Execute until all tasks are done or require manual intervention.
 +workflow.complete_all()
```

This will run all tasks using default choices not respecting task spec definitions flagged as manual. How does one "require manual intervention"?

**Comment by knipknap** [comment]
I agree that the documentation is very unclear regarding this point. A better way to say it is:

> complete_all() completes all tasks in accordance to the specification, until no further tasks are READY for being executed.
> Note that this does not mean that the workflow is completed after calling complete_all(), since some tasks may be WAITING, or may be blocked by another WAITING task, for example.

Does this answer your question?

**Comment by jayste** [comment]
Makes sense... My issue is that I am copy pasting this task spec from the tutotial: https://github.com/knipknap/SpiffWorkflow/blob/master/doc/tutorial/nuclear.json

Running complete_all() will complete the workflow even though some are defined as manual tasks with workflow_aborted getting trigger.

How would I adjust the tutorial so that it would wait for the manual input on the exclusive choice?

**Comment by knipknap** [comment]
Good question... there is currently no built-in "complete_all_except_manual()" yet. Currently the only way to do this is to use iterate over the tasks, similar to how complete_next() is implemented:

https://github.com/knipknap/SpiffWorkflow/blob/master/SpiffWorkflow/workflow.py#L211

Except you'd need to check the "manual" flag before calling complete() on the task.
