### ISSUE TITLE
doc/tutorial/deserialize.py is failing

### ISSUE THREAD

**Issue by tinck** [sartography/SpiffWorkflow#53]
After doc/tutorial/deserialize.py was executed, I run deserialize.py

Traceback (most recent call last):
  File "deserialize.py", line 8, in <module>
    spec = WorkflowSpec.deserialize(serializer, workflow_json, 'nuclear.json')
TypeError: deserialize() takes 3 positional arguments but 4 were given

**Comment by knipknap** [comment]
I just committed a fix in ee84959904e03783f79be2d0244b60e10cc6be13

**Comment by tinck** [comment]
Thanks, but after ee84959 another error occured, when running deserialize.py
@knipknap 

Traceback (most recent call last):
  File "deserialize.py", line 7, in <module>
    spec = WorkflowSpec.deserialize(serializer, workflow_json)
  File "/home/x/code/python/venv/workflow/lib/python3.5/site-packages/SpiffWorkflow/specs/WorkflowSpec.py", line 136, in deserialize
    return serializer.deserialize_workflow_spec(s_state, **kwargs)
  File "/home/x/code/python/venv/workflow/lib/python3.5/site-packages/SpiffWorkflow/serializer/json.py", line 66, in deserialize_workflow_spec
    return super(JSONSerializer, self).deserialize_workflow_spec(thedict, **kwargs)
  File "/home/x/code/python/venv/workflow/lib/python3.5/site-packages/SpiffWorkflow/serializer/dict.py", line 424, in deserialize_workflow_spec
    spec = WorkflowSpec(s_state['name'], filename=s_state['file'])
TypeError: string indices must be integers

**Comment by knipknap** [comment]
This sounds like your workflow spec may be wrong. Does your JSON contain the "name" and "file" fields?

**Comment by tinck** [comment]
After running the code 
`open('workflow-spec.json', 'w').write(pretty)`
in serialilze.py, the program outputs JSON string into workflow-spec.json, which I used in deserialize.py.
And the JSON string is

"{\"description\": \"\", \"file\": null, \"name\": \"\", \"task_specs\": {\"Start\": {\"class\": \"SpiffWorkflow.specs.StartTask.StartTask\", \"data\": {}, \"defines\": {}, \"description\": \"\", \"id\": 1, \"inputs\": [], \"internal\": false, \"locks\": [], \"lookahead\": 2, \"manual\": false, \"name\": \"Start\", \"outputs\": [\"general\"], \"post_assign\": [], \"pre_assign\": []}, \"general\": {\"choice\": null, \"class\": \"SpiffWorkflow.specs.ExclusiveChoice.ExclusiveChoice\", \"cond_task_specs\": [[[\"SpiffWorkflow.operators.Equal\", [[\"Attrib\", \"confirmation\"], [\"value\", \"yes\"]]], \"president\"]], \"data\": {}, \"default_task_spec\": \"workflow_aborted\", \"defines\": {}, \"description\": \"\", \"id\": 2, \"inputs\": [\"Start\"], \"internal\": false, \"locks\": [], \"lookahead\": 2, \"manual\": false, \"name\": \"general\", \"outputs\": [\"workflow_aborted\", \"president\"], \"post_assign\": [], \"pre_assign\": []}, \"nuclear_strike\": {\"class\": \"SpiffWorkflow.specs.Simple.Simple\", \"data\": {}, \"defines\": {}, \"description\": \"\", \"id\": 5, \"inputs\": [\"president\"], \"internal\": false, \"locks\": [], \"lookahead\": 2, \"manual\": false, \"name\": \"nuclear_strike\", \"outputs\": [], \"post_assign\": [], \"pre_assign\": []}, \"president\": {\"choice\": null, \"class\": \"SpiffWorkflow.specs.ExclusiveChoice.ExclusiveChoice\", \"cond_task_specs\": [[[\"SpiffWorkflow.operators.Equal\", [[\"Attrib\", \"confirmation\"], [\"value\", \"yes\"]]], \"nuclear_strike\"]], \"data\": {}, \"default_task_spec\": \"workflow_aborted\", \"defines\": {}, \"description\": \"\", \"id\": 4, \"inputs\": [\"general\"], \"internal\": false, \"locks\": [], \"lookahead\": 2, \"manual\": false, \"name\": \"president\", \"outputs\": [\"workflow_aborted\", \"nuclear_strike\"], \"post_assign\": [], \"pre_assign\": []}, \"workflow_aborted\": {\"cancel_successfully\": false, \"class\": \"SpiffWorkflow.specs.Cancel.Cancel\", \"data\": {}, \"defines\": {}, \"description\": \"\", \"id\": 3, \"inputs\": [\"general\", \"president\"], \"internal\": false, \"locks\": [], \"lookahead\": 2, \"manual\": false, \"name\": \"workflow_aborted\", \"outputs\": [], \"post_assign\": [], \"pre_assign\": []}}}"

**Comment by knipknap** [comment]
Ah, the error was in serialize.py. Fix is committed.

**Comment by tinck** [comment]
Problem solved, Thanks.
