### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by junaidiiith** [sartography/SpiffWorkflow#54]
Here http://spiffworkflow.readthedocs.io/en/latest/tutorial/index.html, in the json, the president task
```
"president": {
            "class": "SpiffWorkflow.specs.ExclusiveChoice.ExclusiveChoice",
            "name": "president",
            "manual": true,
            "inputs": [
                "general"
            ],
            "outputs": [
                "workflow_aborted",
                "nuclear_strike"
            ],
            "choice": null,
            "default_task_spec": "workflow_aborted",
            "cond_task_specs": [
                [
                    [
                        "SpiffWorkflow.operators.Equal",
                        [
                            [
                                "Attrib",
                                "confirmation"
                            ],
                            [
                                "value",
                                "yes"
                            ]
                        ]
                    ],
                    "president"
                ]
            ]
        }
```
Here in the output task if the condition is true, president is given. I think it should be nuclear_strike.

**Comment by knipknap** [comment]
Thanks for the heads up! :+1:

**Comment by junaidiiith** [comment]
I don't see the change in the documentation, if I was wrong, could you tell me how?

**Comment by knipknap** [comment]
I see it online. You probably need to "shift-reload" the page.

**Comment by junaidiiith** [comment]
Okay so, if I have a workflow specification in json, how do I go about
executing it after deserializing it? For eg. I tried nuclear.json as in the
tutorial and for the president and general task being manual it should ask
me the input right. But I didn't see anything after executing
workflow.complete_all(). Sorry if I'm being naive as I have not read the
entire code.
Also, where am I linking an a file that runs when a particular task is executed?

**Comment by knipknap** [comment]
Spiff Workflow does not implement any user interaction - that is something you need to do in your code. You may also want to check issue #52 .
(I will accept a patch that adds a "manual=False" argument to Workflow.complete_all().)

**Comment by junaidiiith** [comment]
Yeah, but say there's a task X and a library Xlib to execute that task, so when the task is executed that library needs to execute that right, where is that linkage happening?
