### ISSUE TITLE
How to custmize task  by following bpmn 2.0?

### ISSUE THREAD

**Issue by brianling** [sartography/SpiffWorkflow#56]
I am going to implement workflow by following bpmn 2.0
but I don't know how to customize task which can execute job what I want
which task should I override, scriptTask or callActivity or ....?
I am not sure how to implement is correct way
Would you please help me?
Thank you so much

**Comment by knipknap** [comment]
Unfortunately there is no BPMN documentation yet (see issue #51). Here is how the zengine guys did it:

https://github.com/zetaops/zengine/blob/develop/zengine/engine.py#L427

In other words, they do not create a subclass of a task. Instead, they attach a reference to a Python function into task_data, and execute the function whenever they are completing a task.
