### ISSUE TITLE
DMN support

### ISSUE THREAD

**Issue by DennyWeinberg** [sartography/SpiffWorkflow#57]
Hi,

this library does not have a dmn engine (http://demo.bpmn.io/dmn or https://camunda.org/dmn/simulator/) right?

I searched a lot and there is not dmn decoder/engine for python... Am I missing something?
I just found this: https://github.com/jan-klos/dmn_pythonbut this library is not up to date I think... And is not compatible with camunda's xml files.

Thanks

Denny

**Comment by knipknap** [comment]
You are right, there is sadly no DMN engine yet. Given my current work load, I will also probably not be able to create it any time soon.

**Comment by DennyWeinberg** [comment]
Ok. Thanks for the info. I will probabily write some code.

**Comment by knipknap** [comment]
Cool, I'd be happy to merge them.

**Comment by DennyWeinberg** [comment]
See https://github.com/labsolutionlu/bpmn_dmn
