### ISSUE TITLE
Are Input/Output parameters supported?

### ISSUE THREAD

**Issue by DennyWeinberg** [sartography/SpiffWorkflow#58]
Hi,

I am wondering if input/output parameters are supported (I am using Camunda Modeler).

I successfully used an Script Task which does "task.set_data(found='yes')" and then I have an exclusive block that has two outgoing things with expressions: "found=='yes'" and "found!='yes'".

But can't be this done this using input/output parameters. What is a use case for this?
[PizzaSimpleWithScriptTaskAndCondition.bpmn.txt](https://github.com/knipknap/SpiffWorkflow/files/1306750/PizzaSimpleWithScriptTaskAndCondition.bpmn.txt)

**Comment by knipknap** [comment]
I am sorry, but unless someone from Rackspace chimes in I am afraid I won't be able to answer this; I don't know the BPMN emulation very well and currently sadly don't have the time to work myself into it at the moment (unless it's a job, in which case I can be hired).

**Comment by DennyWeinberg** [comment]
Ok, thanks.

**Comment by danfunk** [comment]
I'm cleaning up old or outdated tickets.  The PythonScriptEngine was heavily overhauled recently and we have tested exclusive gateway expressions extensively, there are good examples of how to do this in the tests.
