### ISSUE TITLE
BMPN modeler

### ISSUE THREAD

**Issue by rosperitus** [sartography/SpiffWorkflow#59]
Hello! Which GUI BPMN editor can I use to load to the SpiffWorkflow? Bizagi Modeler 2.6 saves xml not compatible with the SpiffWorkflow/

**Comment by knipknap** [comment]
I am honestly not sure which editor was used for creating our test XML, it was a contribution by the guys from Rackspace. I am happy to accept patches to support more dialects if needed.

**Comment by DennyWeinberg** [comment]
I use the Camunda Modeler. Works perfectly.

**Comment by calexh-sar** [comment]
@rosperitus I am with Sartography and we just released Version 1.0 and would be happy to assist you with this if you don't find anything in the updated [readme docs](https://spiffworkflow.readthedocs.io/en/latest/ if you are still interested.

**Comment by danfunk** [comment]
We are using BPMN.js, and we are currently building an API and extensions to BPMN.js that will allow us to communicate between a front-end user interface and the backend.  This is allowing us to perform real-time validation of the workflows from the editor.  Some of our current efforts are around creating API endpoints that will allow us to create and report to the front end any backend code that can be called from a script task.   While this work was specific to a client, we are now working to generalize it and make those APIs open source as well.  It's just going to take us some time to get there.
