### ISSUE TITLE
Documentation on XML for bpmn

### ISSUE THREAD

**Issue by dickkniep** [sartography/SpiffWorkflow#60]
Hi Guys,
We are trying to implement SpiffWorkflow in an exiting new project. However the documentation of the XML lacks examples and the examples I do find do not work

According to the documentation (and examples I found) the following should work:
```
with open(flow_def, 'r') as xmlflow: 
    xml_data = xmlflow.read() 
    spec = WorkflowSpec.deserialize(XmlSerializer(), xml_data, filename=flow_def)
```
However using this code results in an
```
    E       AttributeError: 'str' object has no attribute 'findtext'
```
Looking at the statement that is executed, this can never work because it expects an lxml object.

**Comment by knipknap** [comment]
Sorry that I didn't get to write any docs yet. I have a lot of projects to work on, and am unlikely to be able to work on this. Unless someone decides to hire me for working on it, I can currently only offer to merge patches. (It is also possible that the code needs work to support the latest versions of some BPMN modelers.)

**Comment by knipknap** [comment]
I am closing this, since there's already an issue open for the docs. (#51).

**Comment by sepulm01** [comment]
Hi, I use this :
This code is for 0.3.5 version i guest:
#from SpiffWorkflow.serializer.xml import XmlSerializer 
#xml = open(filename).read()
#self.wf_spec = WorkflowSpec.deserialize(XmlSerializer(), xml, filename = filename)

I change it for this, in 0.5.22 (latest in pip):
from SpiffWorkflow.serializer.prettyxml import XmlSerializer
with open(filename) as fp:
    serializer = XmlSerializer()
    self.wf_spec = WorkflowSpec.deserialize(serializer, fp.read())

I hope will useful.
