### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by dickkniep** [sartography/SpiffWorkflow#61]
When an error occurs in a scripttask the workflow is aborted. Is there a more subtle way to handle exceptions within Spiff?

**Comment by knipknap** [comment]
There was a question about adding an explicit ERROR state in #13, you might want to look at my answer there. In short: I currently don't see a use case where have an explicit ERROR state would help.

Or is there another use case that you would like to simplify?

**Comment by calexh-sar** [comment]
@dickkniep please let us know if you need any additional assistance with this ticket.

**Comment by danfunk** [comment]
We've worked to create and apply a WorkflowException which contains detailed information about workflow execution errors.  While it isn't perfect (What would be about errors?) it does give you very detailed reporting on the specific task where the error occurred.  In the case of a script task that uses the PythonExecutionEngine, we can even return the exact line in the script that caused the problem.
