### ISSUE TITLE
Crash while compiling with cxFreeze, Py2Exe and PyInstaller

### ISSUE THREAD

**Issue by dickkniep** [sartography/SpiffWorkflow#62]
When compiling an application that uses SpiffWorkflow into an exe the resulting exe crashes with "ImportError: No module named UserList"

The result is the same for all 3 tools to compile the application.

I have traced this back to the statements in the Packager under BPMN:

`from future import standard_library
standard_library.install_aliases()`

As far as I understand this is only needed to allow configparser to be found in Python2 and 3. However, in the last version of 2.7 this has been taken care of. So I wonder if these lines can be safely removed?

**Comment by knipknap** [comment]
I think you are right, none of the modules this provides are actually being used. So this code should not be needed. (I have just pushed this to master.)
