### ISSUE TITLE
Support for ServiceTask ?

### ISSUE THREAD

**Issue by keklesurvivant** [sartography/SpiffWorkflow#63]
Hello ! 

I noticed there was an implementation of ServiceTask in the forked version for ZEngine : https://github.com/zetaops/SpiffWorkflow/blob/master/SpiffWorkflow/bpmn/specs/ServiceTask.py

As I'm using the original repository for its LGPL 3 license, I was wondering if there is any plan to backport this class. I'm indeed a little bit confused by the LGPL 2.1 licence mentionned in the class file header...

**Comment by calexh-sar** [comment]
@keklesurvivant  I am with Sartography and we just released Version 1.0 and would be happy to assist you with this if you don't find anything in the updated [readme docs](https://spiffworkflow.readthedocs.io/en/latest/ if you are still interested.

**Comment by danfunk** [comment]
We should definitely take time to clean up the headers and assure we have a consistent license.

**Comment by danfunk** [comment]
Closing this, adding a ticket to create consistent headers and licenses.
