### ISSUE TITLE
exclusive-choice conditional-successor successor is join run empty task

### ISSUE THREAD

**Issue by maplye** [sartography/SpiffWorkflow#67]
After run test code, I want get current task **collect_change**, but now is empty!

test code:

    def test_swprocess(self):
        serializer = XmlSerializer()
        xml_file = 'tests/docs/swprocess.xml'
        xml_data = open(xml_file).read()
        spec = serializer.deserialize_workflow_spec(xml_data)
        wf = Workflow(spec)
        tasks = wf.get_tasks(Task.READY)
        task = tasks[0]
        wf.complete_task_from_id(task.id)
        # start
        tasks = wf.get_tasks(Task.READY)
        print('tasks ...')
        print(tasks)
        task = tasks[0]
        task.set_data(**{'process_type': 'sw_optimization'})
        wf.complete_task_from_id(task.id)
        # start
        tasks = wf.get_tasks(Task.READY)
        print('tasks 1...')
        print(tasks)
        task = tasks[0]
        self.assertEqual('internal_sw_optimization', task.get_name())
        # internal_sw_optimization
        wf.complete_task_from_id(task.id)
        tasks = wf.get_tasks(Task.READY)
        task = tasks[0]
        self.assertEqual('code_implementation', task.get_name())
        # code_implementation
        wf.complete_task_from_id(task.id)
        tasks = wf.get_tasks(Task.READY)
        task = tasks[0]
        self.assertEqual('project_build', task.get_name())
        # project_build
        wf.complete_task_from_id(task.id)
        tasks = wf.get_tasks(Task.READY)
        task = tasks[0]
        self.assertEqual('pre_validation', task.get_name())
        # pre_validation
        wf.complete_task_from_id(task.id)
        tasks = wf.get_tasks(Task.READY)
        task = tasks[0]
        self.assertEqual('collect_change', task.get_name())
        # collect_change
        wf.complete_task_from_id(task.id)
        tasks = wf.get_tasks(Task.READY)
        task = tasks[0]
        self.assertEqual('code_review_meeting', task.get_name())
        # code_review_meeting
        wf.complete_task_from_id(task.id)
        tasks = wf.get_tasks(Task.READY)
        task = tasks[0]
        self.assertEqual('sw_change_class', task.get_name())
        # sw_change_class
        wf.complete_task_from_id(task.id)
        tasks = wf.get_tasks(Task.READY)
        task = tasks[0]
        self.assertEqual('review_code_issues', task.get_name())
        # review_code_issues
        task.set_data(**{'review_result': 'N'})
        wf.complete_task_from_id(task.id)
        tasks = wf.get_tasks(Task.READY)
        print(tasks)
        task = tasks[0]
        self.assertEqual('collect_change', task.get_name())

swprocess.xml:

    <?xml version="1.0" encoding="UTF-8"?> 
    <process-definition name="flow" revision="1.6">
        <description>CEP Software Release Process</description>

        
        <start-task>
            <successor>process_type</successor>
        </start-task>

        <multi-choice name="process_type">
            <description>Select Process Type</description>
            
            
            
            
            <conditional-successor>
                <equals left-field="process_type" right-value="new_product" />
                <successor>test_plan_creation</successor>
            </conditional-successor>
            <conditional-successor>
                <equals left-field="process_type" right-value="new_product" />
                <successor>validation_plan_definition</successor>
            </conditional-successor>
            <conditional-successor>
                <equals left-field="process_type" right-value="new_product" />
                <successor>repository_creation</successor>
            </conditional-successor>

            
            <conditional-successor>
                <equals left-field="process_type" right-value="new_sw_project" />
                <successor>repository_creation</successor>
            </conditional-successor>

            
            <conditional-successor>
                <equals left-field="process_type" right-value="ecn_pcn" />
                <successor>process_env_change</successor>
            </conditional-successor>

            
            <conditional-successor>
                <equals left-field="process_type" right-value="sw_optimization" />
                <successor>internal_sw_optimization</successor>
            </conditional-successor>
        </multi-choice>

        <multi-choice name="process_env_change">
            <description>Process evironment change</description>
            
            <conditional-successor>
                <equals left-field="need_test_plan" right-value="True" />
                <successor>test_plan_creation</successor>
            </conditional-successor>
            <conditional-successor>
                <equals left-field="need_validation_plan" right-value="True" />
                <successor>validation_plan_definition</successor>
            </conditional-successor>
            <conditional-successor>
                <equals left-field="need_code_change" right-value="True" />
                <successor>code_implementation</successor>
            </conditional-successor>
        </multi-choice>

        <task name="repository_creation">
            <description>Repository creation</description>
            <successor>code_implementation</successor>
        </task>

        <task name="test_plan_creation">
            <description>Test plan creation</description>
            <successor>collect_change</successor>
        </task>

        <task name="validation_plan_definition">
            <description>Validation plan definition</description>
            <successor>collect_change</successor>
        </task>

        <task name="internal_sw_optimization">
            <description>Internal software optimization</description>
            <successor>code_implementation</successor>
        </task>

        <task name="code_implementation">
            <description>Code implementation</description>
            <successor>project_build</successor>
        </task>

        <task name="project_build">
            <description>Project build</description>
            <successor>pre_validation</successor>
        </task>

        <task name="pre_validation">
            <description>Pre-Validation</description>
            <successor>collect_change</successor>
        </task>

        
        
        
        <join name="collect_change" context="process_type" threshold="1">
            <description>Collect Changes</description>
            <successor>code_review_meeting</successor>
        </join>

        <task name="code_review_meeting">
            <description>Code Review Meeting</description>
            <successor>sw_change_class</successor>
        </task>
        <task name="sw_change_class">
            <description>Software Change Classification</description>
            <successor>review_code_issues</successor>
        </task>

        <exclusive-choice name="review_code_issues">
            <description>Review code issues</description>
            <default-successor>selection_tests</default-successor>
            <conditional-successor>
                <equals left-field="review_result" right-value="Y" />
                <successor>selection_tests</successor>
            </conditional-successor>
            <conditional-successor>
                <equals left-field="review_result" right-value="N" />
                <successor>collect_change</successor>
            </conditional-successor>
        </exclusive-choice>

        

        <task name="selection_tests">
            <description>Selection of Tests</description>
            <successor>run_measurements</successor>
        </task>

        <task name="run_measurements">
            <description>Run Measurements</description>
            <successor>evaluate_measurements</successor>
        </task>

        <task name="evaluate_measurements">
            <description>Evaluate Measurements</description>
            <successor>document_collection</successor>
        </task>

        <task name="document_collection">
            <description>Document Collection</description>
            <successor>sw_compliance_approval</successor>
        </task>

        <exclusive-choice name="sw_compliance_approval">
            <description>Software Compliance Approval</description>
            <default-successor>update_sw_release_table</default-successor>
            <conditional-successor>
                <equals left-field="approval_result" right-value="Y" />
                <successor>update_sw_release_table</successor>
            </conditional-successor>
            <conditional-successor>
                <equals left-field="approval_result" right-value="M" />
                <successor>document_collection</successor>
            </conditional-successor>
            <conditional-successor>
                <equals left-field="approval_result" right-value="N" />
                <successor>collect_change</successor>
            </conditional-successor>
        </exclusive-choice>

        <task name="update_sw_release_table">
            <description>Update Software Release Table</description>
            <successor>end</successor>
        </task>

    </process-definition>

**Comment by calexh-sar** [comment]
@maplye I am with Sartography and we just released Version 1.0 and would be happy to assist you with this if you don't find anything in the updated [readme docs](https://spiffworkflow.readthedocs.io/en/latest/ if you are still interested.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
