### ISSUE TITLE
enforce 80 character lines (pep8?)

### ISSUE THREAD

**Issue by faassen** [sartography/SpiffWorkflow#70]
pep8 goes for 80 character lines, but I noticed some files have much longer lines, in particular some of the BPMN stuff. Would it be okay to enforce 80 character lines throughout the codebase?

**Comment by knipknap** [comment]
80 chars is fine with me. This should already be the case everywhere except in the bpmn submodule.

**Comment by calexh-sar** [comment]
@faassen  I am with Sartography and we just released [Version 1.0](https://github.com/sartography/SpiffWorkflow/releases/tag/1.0) and would appreciate if you would confirm that this issue has been addressed and the issue can be closed.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
