### ISSUE TITLE
Timer events or Tasks

### ISSUE THREAD

**Issue by gvandyk** [sartography/SpiffWorkflow#75]
I am struggling to find documentation on how to use timer events and/ or tasks. I need them for escalations and notifications when users do not act within a certain time period to tasks. 

Where can I find directions on how this works, or pointers on how to implement such behaviour.

**Comment by calexh-sar** [comment]
@gvandyk  I am with Sartography and we just released [Version 1.0](https://github.com/sartography/SpiffWorkflow/releases/tag/1.0) and would be happy to assist you with this if you are still interested.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
