### ISSUE TITLE
Is it possible to update data in the middle?

### ISSUE THREAD

**Issue by qiwihui** [sartography/SpiffWorkflow#77]
I am quite confused that as for the example of nuclear strike, how to modify attribute `confirmation` when task is processing?

**Comment by AlvaroRSchmidt** [comment]
Same too. Custom Nuclear Strike is not executed because confirmation is never set to yes. I've been debugging the code, reading the docs, trying to figure out how to set data within the workflow with no success :-(

**Comment by calexh-sar** [comment]
@qiwihui , @ncastrohub and @AlvaroRSchmidt  I am with Sartography and we just released Version 1.0 and would be happy to assist you with this if you don't find anything in the updated [readme docs](https://spiffworkflow.readthedocs.io/en/latest/) if you are still interested.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
