### ISSUE TITLE
Linking my class to a <task> xml node

### ISSUE THREAD

**Issue by ghost** [sartography/SpiffWorkflow#80]
Hi,

Can someone please provide an example of how to link a Simple task derivative to the <task> node?.  All <task>s are by default treated as "Simple" type. What if I want to get my own derivative of Simple instead as the task spec? The NuclearStrike example is very clear for JSON, is there a similar one for the XML? I searched all over the internet, can't find a clear example for XML.

For the JSON example, I can see where this binding happens using the 'class' attribute - in dict.py
            task_spec_cls = get_class(task_spec_state['class'])
            task_spec = task_spec_cls.deserialize(self, spec, task_spec_state)

Is there a similar thing for XML. I tried providing a class attribute on the task node, but it obviously didn't work because there is no code in the XML Serializer consuming and acting on that.

**Comment by lbenda** [comment]
You must implement your own serializer deserializer. For JSON it's shown in the manual, same you should do it for XML. It's dosn't run out of the box.

**Comment by calexh-sar** [comment]
@trivicks  I am with Sartography and we just released Version 1.0 and would be happy to assist you with this if you don't find anything in the updated [readme docs](https://spiffworkflow.readthedocs.io/en/latest/) if you are still interested.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
