### ISSUE TITLE
CompactWorkflowSerializer incorrectly deserializes state of Parallel Gateway

### ISSUE THREAD

**Issue by schetv** [sartography/SpiffWorkflow#82]
I have a simple BPMN 2.0 workflow with a parallel split, two tasks running in parallel and a join - see attached.

I progress my workflow to a state where both tasks are complete, and my Join Parallel Gateway is set to READY state.

If I serialize  the workflow at this stage and then deserialize it back, CompactWorkflowSerializer sets the state of the Join Parallel Gateway to WAITING.

I am attaching a BPMN 2.0 diagram and a code snippet that can be used to reproduce the issue.

[incorrect-deserialization.zip](https://github.com/knipknap/SpiffWorkflow/files/1744092/incorrect-deserialization.zip)

**Comment by calexh-sar** [comment]
@schetv  I am with Sartography and we just released Version 1.0 and would be happy to assist you with this if you don't find anything in the updated [readme docs](https://spiffworkflow.readthedocs.io/en/latest/ if you are still interested.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
