### ISSUE TITLE
Can i save a running workflow instance?

### ISSUE THREAD

**Issue by kokkoon** [sartography/SpiffWorkflow#83]
In the event if a task is waiting for a response from human, can the running workflow be saved and resumed only after the task has been executed? I don't see any doc on that or i must have missed it?

**Comment by calexh-sar** [comment]
@kokkoon I am with Sartography and we just released [Version 1.0](https://github.com/sartography/SpiffWorkflow/releases/tag/1.0) and would be happy to assist you with this if you don't find anything in the updated [readme docs](https://spiffworkflow.readthedocs.io/en/latest/ if you are still interested.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
