### ISSUE TITLE
Workflow global data

### ISSUE THREAD

**Issue by biggosh** [sartography/SpiffWorkflow#84]
Hi,

I'm asking if it's possible to set a value at workflow level so I can set the value once (when it's available) and then use it in multiple tasks. Is it possible?

I read there is a get_data in workflow class but I'm not able to find how to set this data.

thanks

**Comment by calexh-sar** [comment]
@biggosh please let us know if you still need any assistance with this issue.

**Comment by biggosh** [comment]
Hi.
I took the code and I rewrote many parts of it to simplify and have what I need.

Now it's specific for the usage I needed 3 years ago, so it's not so useful to share the code even if I tried (but i have no time) to merge the two branches and release something.
Thanks

**Comment by calexh-sar** [comment]
@biggosh thanks for the update.  We also rewrote many existing parts as well as added new features.  If you have time in the future or another project that needs workflow capabilities, we would appreciate you taking a look at what we have again.
