### ISSUE TITLE
Join can't be write by hand to JSON

### ISSUE THREAD

**Issue by lbenda** [sartography/SpiffWorkflow#88]
Hello, deserializer expected treshold serialized by pickle and to base64. So this is something which is nearly impossible write by hand, only possibility is to generate this node by serialization.

**Comment by junior1q94** [comment]
I have also encountered that problem, I think the JSON serializer is not as complete as the xml serializer. 

In my case I do not see the need to serialize the value that way, so I worked around like this: https://github.com/knipknap/SpiffWorkflow/pull/95/files

If someone could explain why it is important to serialize by pickle and base64 it would be great.

**Comment by calexh-sar** [comment]
@lbenda and @junior1q94 I am with Sartography and we just released [Version 1.0](https://github.com/sartography/SpiffWorkflow/releases/tag/1.0) which may have addressed this issue if you are still interested.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
