### ISSUE TITLE
Documentation states BPMN supports Inclusive Gateways but it doesn't?

### ISSUE THREAD

**Issue by marcosgeorgopoulos** [sartography/SpiffWorkflow#89]
When trying to use an inclusive gateway with two outgoing sequence flows I get this error.

SpiffWorkflow.bpmn.parser.ValidationException.ValidationException: Multiple outgoing flows are not supported for tasks of type
Source Details: bpmn:inclusiveGateway

Are we expected to subclass 'handles_multiple_outgoing' to get this working?

**Comment by calexh-sar** [comment]
@marcosgeorgopoulos I am with Sartography and we just released [Version 1.0](https://github.com/sartography/SpiffWorkflow/releases/tag/1.0) which may have addressed your issue if you are still interested.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
