### ISSUE TITLE
设备报修管理的审批工作流程，是否适用于SpiffWorkflow

### ISSUE THREAD

**Issue by lovefox666** [sartography/SpiffWorkflow#90]
有以下应用场景：
1、用户有设备需要报修，填写了设备缺陷信息。提交给设备管理部门
2、设备管理部门获取缺陷信息后，评估缺陷，并填写预估费用，提交给部门领导审批。
3、领导审批后，技术人员组织维修设备，并反馈维修结果。
4、用户获取维修结果反馈，验收设备，并给出评价。

**Comment by knipknap** [comment]
Sorry, I don't understand what this issue is about. Please file issues in English. -Samuel
