### ISSUE TITLE
How to Run SpiffWorkFlow Using Python?

### ISSUE THREAD

**Issue by mani140249** [sartography/SpiffWorkflow#91]
Iam Using Linux Operating System to Run the project..So help me to run the project using command based

**Comment by calexh-sar** [comment]
I am with Sartography and we just released [Version 1.0](https://github.com/sartography/SpiffWorkflow/releases/tag/1.0) and believe you will find the answer to your question in the [readme docs](https://spiffworkflow.readthedocs.io/en/latest/) if you are still interested.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
