### ISSUE TITLE
Is this project still supported or commercially supported?

### ISSUE THREAD

**Issue by me1kd** [sartography/SpiffWorkflow#92]
As title: 
Is this project still supported or commercially supported?

I also notice https://procedure8.com/, the commercial supporter returns 502 (30/04/2019)

**Comment by calexh-sar** [comment]
@me1kd I am with Sartography and we just released [Version 1.0](https://github.com/sartography/SpiffWorkflow/releases/tag/1.0) if you are still interested.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
