### ISSUE TITLE
reading bpmn workflow using spiffworkflow

### ISSUE THREAD

**Issue by siva-chaduvula** [sartography/SpiffWorkflow#98]
from SpiffWorkflow.bpmn.specs.BpmnProcessSpec import BpmnProcessSpec
from SpiffWorkflow.bpmn.serializer.BpmnSerializer import BpmnSerializer
from SpiffWorkflow.bpmn.workflow  import BpmnWorkflow

# Load the workflow specification:
with open('bpmn_workflow.xml') as fp:
    serializer = BpmnSerializer()
    spec = BpmnProcessSpec.deserialize(serializer, fp.read())
wf = BpmnWorkflow(spec)
wf

# I am getting the following error
<img width="1056" alt="Capture" src="https://user-images.githubusercontent.com/9678190/72376160-7eb8cf00-36db-11ea-9c7b-83bd4b63f070.PNG">

Can you help me what is going wrong? Thanks

**Comment by calexh-sar** [comment]
@siva-chaduvula I am with Sartography and we just released [Version 1.0](https://github.com/sartography/SpiffWorkflow/releases/tag/1.0) and this issue likely was addressed if you are still interested.  Please let us know if you see otherwise and/or would like to discuss further.

**Comment by calexh-sar** [comment]
Closing this issue due to age and lack of response.
